[package]
name = "fugue-sleighc"
version = "0.3.0"
authors = ["Sam L. Thomas <st@xv.ax>"]
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Wrapper around Ghidra's SLEIGH specification compiler"
homepage = "https://fugue.re"

[dependencies]
thiserror = "2"

[build-dependencies]
cmake = "0.1"
